### ISSUE TITLE
Sparrow Parsing Some Taproot UTXOs Incorrectly on Signet

### ISSUE THREAD

**Issue by 0xAether** [sparrowwallet/sparrow#1798]
Firstly, I'd like to thank you for developing Sparrow. It's by far the best wallet I've found and meets all of the needs I have and will have in the future. Second, I'd like to apologize in advance if I don't use the correct terminology somewhere, I'm not a software developer nor a Bitcoin expert.

### My Setup
- Host OS: Windows 11 24H2
- Sparrow version: 2.2.3 installed from MSI release
- Sparrow wallet: Taproot
- Bitcoin Core version (what Sparrow is connected to) : 29.0.0 running on the same system as Sparrow (Windows 11 24H2) via RPC.
- Bitcoin network is Signet for everything I'm referring to in this issue.

### Issue
After exhausting all other avenues I can possibly think of I have a feeling this is an issue with how Sparrow is parsing some Taproot UTXOs. I've obtained some Signet BTC via ajtowns/powcoins script hosted here on Github for testing and learning purposes. Most of the UTXOs I receive from this script is spendable and works as expected. However, some of them I cannot send/consolidate. On UTXOs that I can send/consolidate, I notice that the ID of the UTXO matches the "Outpoint" field in the "Input" section of a new TX. On UTXOs that I've having this issue with, the ID in the "Outpoint" field is different than the UTXO ID, doesn't exist on the Signet blockchain, and is shown by sparrow as "External".

One such UTXO is [4e3cd921b44cb5ef91fd5791f5bf2c979c8891c0a86ede8347997f49305a0f4c](https://mempool.space/signet/tx/4e3cd921b44cb5ef91fd5791f5bf2c979c8891c0a86ede8347997f49305a0f4c). The ID that Sparrow will display for this UTXO in the new TX screen is 373768c4d6bbf55348b63de32ff9413caae959ac5d0ddf1ec21a778bc1fea24a which [doesn't exist](https://mempool.space/signet/tx/373768c4d6bbf55348b63de32ff9413caae959ac5d0ddf1ec21a778bc1fea24a).

When I attempt to spend this UTXO, the error message I receive by Sparrow after I attempt to broadcast the TX says "The server returned an error indicating some or all of the UTXOs this transaction is spending are missing or have already been spent."

After looking in the log file (attached in its entirety) I see the following excerpt that appears to me is the source of the issue.

```
2025-07-20 09:37:54,104 WARN [JavaFX Application Thread] c.s.s.w.TransactionEntry [null:-1] TransactionEntry 9c33b0f021bb387d7a4e247771bb733d57318dbf4480c6c96711807f6e371dcb for wallet Signet-P2TR has incorrect number of children 1 (should be 0)
2025-07-20 09:37:54,104 WARN [JavaFX Application Thread] c.s.s.w.TransactionEntry [null:-1] TransactionEntry 62dd882b58301367d5af0cf5b5cae12914f594784d5a7b318b68234a806487b0 for wallet Signet-P2TR has incorrect number of children 1 (should be 0)
2025-07-20 09:37:54,105 WARN [JavaFX Application Thread] c.s.s.w.TransactionEntry [null:-1] TransactionEntry 4e5ee76fc4a4a26da9c40b0d1100213b6fbae4c1fef44414b42549f809332201 for wallet Signet-P2TR has incorrect number of children 1 (should be 0)
2025-07-20 09:37:54,105 WARN [JavaFX Application Thread] c.s.s.w.TransactionEntry [null:-1] TransactionEntry d7e41ed8164b191a53ee95b4bff65379b82069dfd8c5cc452e24cdfbaba7c8f7 for wallet Signet-P2TR has incorrect number of children 1 (should be 0)
2025-07-20 09:37:54,105 WARN [JavaFX Application Thread] c.s.s.w.TransactionEntry [null:-1] TransactionEntry 2738e05e4b7284c00bd1e27e8c72ca6d570611a04ea8e55df8ebc316c5c6e198 for wallet Signet-P2TR has incorrect number of children 1 (should be 0)
2025-07-20 09:37:54,105 WARN [JavaFX Application Thread] c.s.s.w.TransactionEntry [null:-1] TransactionEntry 4e3cd921b44cb5ef91fd5791f5bf2c979c8891c0a86ede8347997f49305a0f4c for wallet Signet-P2TR has incorrect number of children 1 (should be 0)
2025-07-20 09:37:54,106 WARN [JavaFX Application Thread] c.s.s.w.WalletTransactionsEntry [null:-1] Removing and not notifying incomplete entry 9c33b0f021bb387d7a4e247771bb733d57318dbf4480c6c96711807f6e371dcb value 12499454 children [Output 9c33b0f021bb387d7a4e247771bb733d57318dbf4480c6c96711807f6e371dcb:0]
2025-07-20 09:37:54,106 WARN [JavaFX Application Thread] c.s.s.w.WalletTransactionsEntry [null:-1] Removing and not notifying incomplete entry 4e3cd921b44cb5ef91fd5791f5bf2c979c8891c0a86ede8347997f49305a0f4c value 12499636 children [Output 4e3cd921b44cb5ef91fd5791f5bf2c979c8891c0a86ede8347997f49305a0f4c:0]
2025-07-20 09:37:54,106 WARN [JavaFX Application Thread] c.s.s.w.WalletTransactionsEntry [null:-1] Removing and not notifying incomplete entry d7e41ed8164b191a53ee95b4bff65379b82069dfd8c5cc452e24cdfbaba7c8f7 value 199999632 children [Output d7e41ed8164b191a53ee95b4bff65379b82069dfd8c5cc452e24cdfbaba7c8f7:0]
2025-07-20 09:37:54,106 WARN [JavaFX Application Thread] c.s.s.w.WalletTransactionsEntry [null:-1] Removing and not notifying incomplete entry 2738e05e4b7284c00bd1e27e8c72ca6d570611a04ea8e55df8ebc316c5c6e198 value 99999634 children [Output 2738e05e4b7284c00bd1e27e8c72ca6d570611a04ea8e55df8ebc316c5c6e198:0]
2025-07-20 09:37:54,106 WARN [JavaFX Application Thread] c.s.s.w.WalletTransactionsEntry [null:-1] Removing and not notifying incomplete entry 4e5ee76fc4a4a26da9c40b0d1100213b6fbae4c1fef44414b42549f809332201 value 199999632 children [Output 4e5ee76fc4a4a26da9c40b0d1100213b6fbae4c1fef44414b42549f809332201:0]
2025-07-20 09:37:54,106 WARN [JavaFX Application Thread] c.s.s.w.WalletTransactionsEntry [null:-1] Removing and not notifying incomplete entry 62dd882b58301367d5af0cf5b5cae12914f594784d5a7b318b68234a806487b0 value 199999448 children [Output 62dd882b58301367d5af0cf5b5cae12914f594784d5a7b318b68234a806487b0:0]
2025-07-20 09:47:50,321 ERROR [pool-5-thread-1] c.g.a.s.s.JsonRpcServer [null:-1] Error while processing: Request{jsonrpc=2.0, method=blockchain.transaction.get, id=152, params=["373768c4d6bbf55348b63de32ff9413caae959ac5d0ddf1ec21a778bc1fea24a",true]}
java.lang.RuntimeException: com.sparrowwallet.sparrow.net.cormorant.electrum.TransactionNotFoundException: Invalid or non-wallet transaction id
	at simple.json.rpc.server@1.3/com.github.arteam.simplejsonrpc.server.JsonRpcServer.handleSingle(Unknown Source)
	at simple.json.rpc.server@1.3/com.github.arteam.simplejsonrpc.server.JsonRpcServer.handleWrapper(Unknown Source)
	at simple.json.rpc.server@1.3/com.github.arteam.simplejsonrpc.server.JsonRpcServer.handle(Unknown Source)
	at simple.json.rpc.server@1.3/com.github.arteam.simplejsonrpc.server.JsonRpcServer.handle(Unknown Source)
	at com.sparrowwallet.sparrow@2.2.3/com.sparrowwallet.sparrow.net.cormorant.electrum.RequestHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.cormorant.electrum.TransactionNotFoundException: Invalid or non-wallet transaction id
	at com.sparrowwallet.sparrow@2.2.3/com.sparrowwallet.sparrow.net.cormorant.electrum.ElectrumServerService.getTransaction(Unknown Source)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	... 8 common frames omitted
```

As a frame of referenece, an example of a UTXO I'm able to send and is displayed correctly in Sparrow's new TX window is [05f1ebde54a1b81a6ef5723db533aa6e28eff61f0c57b5bfad1b33a49979d807](https://mempool.space/signet/tx/05f1ebde54a1b81a6ef5723db533aa6e28eff61f0c57b5bfad1b33a49979d807).

### Things I've Tried So Far
- Install the same version of Bitcoin Core on a fresh system, downloaded the entire (non-pruned) Signet blockchain, installed the same version of Sparrow and saw the same behavior.
- Generated an unsigned transaction with Bitcoin Core attempting to spend this problematic UTXO and attempted to sign this transaction with Sparrow. Sparrow didn't sign the transaction since it parsed this UTXO in the same incorrect way.
- Deleted my Sparrow Signet wallet and recreated it with my BIP39 seed phrase and saw the same behavior.

Please see the attached screenshots and Sparrow log. If you need me to clarify any of this or if you need more information, I'd be happy to provide it. Thank you in advance!

[log.txt](https://github.com/user-attachments/files/21529295/log.txt)

<img width="362" height="292" alt="Image" src="https://github.com/user-attachments/assets/f853b0bd-51ae-4d30-80bf-fe1e94c60dc4" />
<img width="1919" height="953" alt="Image" src="https://github.com/user-attachments/assets/e8133a12-0014-418e-b02d-b4ebe83b1409" />
<img width="1919" height="948" alt="Image" src="https://github.com/user-attachments/assets/ed54c0ac-180c-4cea-883b-6e5c6d80904b" />
<img width="1717" height="598" alt="Image" src="https://github.com/user-attachments/assets/1afc51f9-c6fe-45b4-9f15-30441866b14b" />

**Comment by craigraw** [comment]
Thanks for reporting this. There was indeed an issue serialising single byte witness elements with a value of zero (which occurred in the reported transaction), and which probably accounts for the strange behaviour you experienced. Fixed in https://github.com/sparrowwallet/drongo/commit/92c57d276c934d43d981b461479585d0afd1eb3e.

**Comment by 0xAether** [comment]
Thank you for taking a look, @craigraw ! When I have some time I'll build from source and see if this is fixed for me. I can't see why it wouldn't be.

**Comment by 0xAether** [comment]
Just to close the loop on this: I built Sparrow from source and I can confirm this fixes my issue. I don't see this issue on the UTXO I referenced nor any other. Thanks again!

**Comment by craigraw** [comment]
Thanks for testing!

**Comment by 0xAether** [comment]
Hi @craigraw

I'm sorry to be the bearer of bad news, however, I'm still seeing some UTXOs not being parsed correctly still with the latest version of Sparrow. The fix you originally implemented for this issue fixed all of the issues I saw when I originally opened this issue, but since then I've been seeing more.

I was able to isolate all 75 UTXOs in my Sparrow signet wallet that aren't being parsed correctly. Below are all of these UTXOs.

I can go ahead and create a new issue for this if you'd like.

`01a54dc2137c2ce814975e90da5093c3cdbf6da1af926d3d8db38aebd8313fc8
08051ff59279382e65625306f49c17776067d812a77b9afcd2a939b1607a3c56
0820cf481cd3543b1b19ea17cb9cd9ff13ca2d4ae2da44d7d581bd63210c64d9
0b407e2449b24dc4ca5480493f67eb8e6e1078670739ec64b4df22175b6e38e0
0d865a0d83aa3728a2c0fcce5592dd44811a0d2f92f9bfd414e46ac8c8388512
0e181fe3aa67afad28d16327931f72325bf00c7e6bfb20b873bb51acfaa8db70
169077b0c804166443afe118c091325b9c626a6ed2fe0c7fd493f6c10250da55
19a5670a2f72c278e0342df745d5dfc581c1faf7c1ae7975e8b9dc5e294996c4
1aa292403759ceaf0f4d49011ddff8f54a81b8da2bc027d5a3ca44663cfcf826
1c1e49ddbe572b3579ad7fc5b0796c970d189942c51269453aabbbe145bba2c3
203242e2df327063d48b66cc78ed34d07a97354e0cec4e2c4aba22f62fc9188e
210ce45b52600f1b8611bbca4aa40bc418b2b8143fe98254fb17231d93875463
26211cae92fb4187b66c7fc350cdde202660430a1771681bb19b01939d84e698
27020afc7f9e02fd434e7fac29d2e70914280822d9b213aea16347729f226b1d
278e96f7998588787ed98fa760afa5f570ba30ecd7ae229d3cc3f5e96521ab47
2ae9a019855f72e48350ed00a98bdf4de6027b19bfc7865ab83b761c46683aa0
2cfc8f360e1cc580472d81c3e00a4785edd7da9ffd2104d5f3f97b4f64c5a980
316a7cd298486ba4edd057e147bb2415acd4d1564582795ef0f55c63fafd0682
3a2281d4d1b8b0239470ead0a37f02cf7c64cf9389dfcd3be9a7aaf73209ceab
416480f02c27d2251e2c4e21f8e9e6e6bddcf89a72f617eed91d411e45f94afb
4ca59bc8ecb881cfac409d0a30f51e298edafef3eae358913e210638900ca1d7
52d179091db34276d3321df5debbbd26071b2db07c1c03dacc8b8cda1344806b
5accd11a9a5a9da5303ee4d792b7a1dbee1569f1c4f18d77bf31e3d77c838611
5d10d41259b1145cdd343399f12d381550b55aadbc4f542321c063e211c8612c
687e587d6196fbbb46d5dd05c0876036cdfb46c21fb3075e4b5ad8177d0fae8d
69a56346879740e4a202e607c2c2bc64ddb73d1bda996ef887e782150d6e2b9f
69ceaa552213d6e2dafcfcfecf3b1e3e7e53922b9545444c3ed550f799323dec
6a35d1c1bed8fdf6b0c70f7dab47db600d1d6e05961cfea0832d80fec08a1d70
6b64d77bb579b0c8bc6a4db81603be1bd97c4a3ab7bc00c64ca762436d59650b
6d4c02473daa09c4bdfe0b985ba61d2edc87db0466e2ee47aef99891d2152df8
6e36b3b3c0076ab6c309e47d8213c93025f457f8f698f7ff0b8ee994713b6f9b
72fae71dcec4efdf5f79980f86e1c39dd9bcdc4590886401724671794ffb09b2
75519684668c178bab84f6d5501166e0ccb66ac9416b640f3cf78f0b60485094
783d5a92a3633ed163bd732af2a7e6f835845145aa24cc7dc8c41f519d6914bf
7cfe23c4cb9f6052e9b90be5ef2a381594de66014875c4e4a72f5e9b2f5498db
7d8f17179205333c2ddf52600344e2e7bfff7701b0b5c3d442e5b36fbba09e58
83ff3739ffc38b40b94b5c524d687cd926c7655f393dab42fe409ece71815dee
884cda918fa5116caefeaeed2d4eae7eedff3f262145447e25da5fa2d918d24f
8982edb71535f3052dc8f7a242073eb63e93b4f11dad4bca886658adb8c38d67
8c0363ec25f7ce431a38ee4b56d0d5d5e8ee7c02910cad4f1cbc430fe9cb7f5c
93087035d172674d7888d494954011842244187804513380c39a6117be6aacb4
9558e4a43b8c3d407b6b89054206db66907a32053ae4bbc3f7969c6c6e9737ff
96853d5b5993fd63e950924c56f84e88a887d6cd14cbe033c40be473249d75cb
984d50d8c3f0e2aac26159509c1ecbb9514f5b83ba4fa46d0a602f96d0bd550a
9d1400ff0dabe9d0ebe1fdda7b765c993fddef42e2922e304b84e23ab6dc6341
9d43cad4f0dea0610bfba45d6d2ad154b8ab89bc80477f2bb0f17d1c6655d86e
a0b6ab988758528c10a76aee033bf73c5345107dfbd7270caa20561fc9ff729c
a3f6392a6e8d9dc0f11fc12a540153f557557cea8119fdf91ca6f34cfcec0436
a8f101c40f384f37e6a28793f13b82720a0c2527e923fa56bb024c665f4659e1
a9c17a90d81e2aab940d188b4517aeb5d47249d09b373f994f7265812a45360f
ae71e16b546d22aa1fe46eaae269acd2be64308920b01d7185498e3b4ce95a9a
b395071be13bb2549b57dedd3d53a05c6a4c1834c0a6b624e53d6f36dc17603f
b64544b855a382fb56b2a3f36fc9d8ee50780e49f48e6daa8a20fa4da28eda7e
b75b5d0ee1735b186c544a88f3e8afd0548f29704f03bd1081e2b8e83e9410d7
bec76057ce7e111c797c08a047468f9ac8e27c6544d6445c36e197b1653df755
c095fa96d67b6371899294a5bc24a6cf8fe9d32f16d8768f5f68f5b7c674c159
c0aad3aaa314514f6df614ad49db04f97826ef9c96b2e3ee828cb3e49278bb84
c5465f0a15dd0519e51988d6149348507389c8c25597b11f36f292aacd7ff3ef
c8b6a0be7b0ecf25e5b3892b33881b88e78a31d7612b00fad3de78eeb1840679
d89f8a34a40f8b101629f45bcb1773eb7424bbc9bd4d3fe47e360c180ee9531d
d8d1735363f4207caff5ecfeeec401c4e939d7bb74405df58c3ea94b3c22ad49
d92252be8fc6de57890295ca4a1733c9cf51452bdf91f686e682f0f4025c8146
db6e12e01dd30d08c3f111670a9d707289cc284668cec5b4437c58c0ac971685
dd9815026648050ac0248a50ab8a8659fed140e4f31a21f49e91b219034ad7d6
e039cf53c0d5d1eaa773f0a34da7446f6f616930eaa8c5c8c039a11fef9ba97d
e0ad510bf4fd30c26bc5700330486a7583fb361de6e70a7e3cbc78669802d4d2
e105f5a57082ddd88b1d5c1a5c3e1d71fb00c76d110244ac9033d53b4e77cc5e
e7e6d0bd1caa2d615abdadbf45d236891db249f697d089e3200ba8897869de93
eab88f3fdc633c293fa91b0c5f67cd02ee2055c0f257266c7dbe90cac40ea7c4
efac3bb7c9dac91bf331e41a4944cf4c6d373e3a362d87e9abfeebfb4dcc4406
f0352b712946e56c7d26d6f9e0564cdf3d15c08843174a3053eb917aa77bcf60
f540a2c949acdda46b483f79ed2683b9d1cd1c8479d23d29d01d6f5fb4bfd755
f8ee5d3f617eaa4b11a8a4ad08dc62a82b3e5844fa8e7f381e683649ac32e504
f977fe5dbe5a01c964ad4f5f1c739b5fa74c82888b0f8f3fd291806f7420bb05
ff7f4b96d2d301144ee23a6c03d5baf7c19041e98ed93eac04c134b326bf69d4`

**Comment by craigraw** [comment]
> I was able to isolate all 75 UTXOs in my Sparrow signet wallet that aren't being parsed correctly. 

Can you describe the error you're seeing?

**Comment by 0xAether** [comment]
> Can you describe the error you're seeing?

@craigraw Sure. It's the same error as originally in this issue. When I go to consolidate or send any of the above 75 UTXOs I get the below error message. I'll attach the log file Sparrow generates as well.

<img width="363" height="294" alt="Image" src="https://github.com/user-attachments/assets/bd1e7a63-413c-4c54-afd6-e37fb8e2f951" />

[log-2025-11-11.txt](https://github.com/user-attachments/files/23479744/log-2025-11-11.txt)

**Comment by craigraw** [comment]
Can you share the full transaction hex from the transaction that produces this error on broadcast? You can copy it from the textarea at the bottom of the transaction tab after attempting broadcast and getting the error above.

**Comment by 0xAether** [comment]
Sure. I attempted to consolidate both `01a54dc2137c2ce814975e90da5093c3cdbf6da1af926d3d8db38aebd8313fc8` and `08051ff59279382e65625306f49c17776067d812a77b9afcd2a939b1607a3c56`

Below is the transaction hex after attempting to broadcast.

`02000000000102aadbe375b83828052086447baeea255d191791f6da251b5b4c91da8dc49feb7b0000000000fdffffff97de5262ed03c503cd7995b4dd1e1fdbb768246fdfc6ae1bf8e2c8e612f2e4d10000000000fdffffff01e798b406000000002251208e4dff013da8e51e63f0d940ed977b0c89936a95d4a7e7420660f6c2f4977acc0140cfbf7efacb5fd43d564da8ad08641e04d1719bd27e911b7b3a71b03b15c163f0e223eb01d1001097e93f8d978fcae0f3df19ddbdc68ffdf5fa533e6baaf2b4d60140f49c0e6436e71bb042befbf0cafb97a30ef64b90a64277ea4b7e9909cbe38297add05775ae81861c134cca07abf226101801edd619f105acce8f2ce3ab52f0fe983d0400`

**Comment by craigraw** [comment]
Thanks. Something definitely appears off since neither of those two txids are reflected as outpoints.

Is there any way you can share an xpub that will retrieve any of these problematic transactions? It would be ideal to be able to construct the tx on my side to see what the problem is. If so, you can email me craig [at] sparrowwallet.com.

**Comment by craigraw** [comment]
Another thought - have you tried refreshing this wallet? See View menu. 

It may be that some old txids from before the fix are hanging around. A refresh (or creating a new wallet) will confirm it.

**Comment by 0xAether** [comment]
I refreshed my wallet and that fixed the issue. I'm sorry for not thinking about that earlier. Thank you for taking a look into it!
